[pytest]

python_files = test_*.py tests_*.py
python_classes = Test*
python_functions = test_*

addopts = -v -s

markers =
    smoke: Smoke Tests
    regression: Regression Tests
    sanity: Sanity Tests
    positive: Positive Test Cases
    negative: Negative Test Cases